# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78ac140b53bb1b0f5978b855aeda50787e304933ba2ee30fb1ab77ee5390ca3579bf40a6dbc014d2f1faa9539f0550d2ac5a5b2eede850bdb6625282953cbffe

test:
  secret_key_base: 12a72b68e1aae70f89c17043f7014b2a155589a568d080897bc61c75034026f4cb936f6cf5a83266273f60ecb83796c6a0822d6d704f37df5f475bc5cce63fe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
